# Generated by Django 5.0.3 on 2024-04-20 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_messages_room_alter_messages_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='required_decency',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
