# Generated by Django 5.0.3 on 2024-05-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='chats/rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='chats/rooms/'),
        ),
    ]
