# Generated by Django 5.0.3 on 2024-05-29 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_category_avatar'),
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='icon_room', to='users.usericon'),
        ),
    ]
