# Generated by Django 5.0.3 on 2024-05-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decency',
            name='last_2_weeks',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='decency',
            name='last_month',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
